---
- name: Configure Read-Only Database Users
  hosts: db_servers
  become: yes
  tasks:
    - name: Install Python MySQL dependencies
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Create app_readonly user with Select permissions
      community.mysql.mysql_user:
        name: app_readonly
        password: sheikh123
        priv: "*.*:SELECT"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
